name: opera
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=23
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=12.1
  - pip:
      - transformers==4.44.0
      - tokenizers==0.19.1
      - accelerate==0.30.1
      - bitsandbytes==0.44.1
      - safetensors>=0.3.1
      - omegaconf
      - hydra-core
      - timm
      - einops
      - iopath
      - opencv-python-headless
      - webdataset
      - pycocotools
      - sentencepiece
      - jupyterlab
